-- Create raw transaction table

USE DATABASE FRAUD_ANALYTICS_DB;
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS TRANSACTIONS_RAW (
    TRANSACTION_ID VARCHAR(50),
    CUSTOMER_ID VARCHAR(50),
    MERCHANT_ID VARCHAR(50),
    TRANSACTION_TIMESTAMP TIMESTAMP_TZ,
    AMOUNT NUMBER(18, 2),
    CURRENCY VARCHAR(10),
    TRANSACTION_TYPE VARCHAR(30),
    PAYMENT_METHOD VARCHAR(30),
    CITY VARCHAR(100),
    STATUS VARCHAR(20),
    INGESTED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
