-- Create customer dimension

USE DATABASE FRAUD_ANALYTICS_DB;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS DIM_CUSTOMER (
    CUSTOMER_ID VARCHAR(50) PRIMARY KEY
);

-- Create merchant dimension

CREATE TABLE IF NOT EXISTS DIM_MERCHANT (
    MERCHANT_ID VARCHAR(50) PRIMARY KEY
);
