-- Create curated transaction fact table

USE DATABASE FRAUD_ANALYTICS_DB;
USE SCHEMA CURATED;

CREATE TABLE IF NOT EXISTS FACT_TRANSACTIONS (
    TRANSACTION_ID VARCHAR(50) PRIMARY KEY,
    CUSTOMER_ID VARCHAR(50),
    MERCHANT_ID VARCHAR(50),
    TRANSACTION_TIMESTAMP TIMESTAMP_TZ,
    AMOUNT NUMBER(18, 2),
    CURRENCY VARCHAR(10),
    TRANSACTION_TYPE VARCHAR(30),
    PAYMENT_METHOD VARCHAR(30),
    CITY VARCHAR(100),
    STATUS VARCHAR(20),
    RISK_SCORE NUMBER(5, 2),
    RISK_LEVEL VARCHAR(20),
    FRAUD_REASONS VARCHAR(500),
    IS_SUSPICIOUS BOOLEAN,
    CREATED_AT TIMESTAMP_TZ DEFAULT CURRENT_TIMESTAMP()
);
