-- Fraud analytics models

USE DATABASE FRAUD_ANALYTICS_DB;
USE SCHEMA CURATED;


-- 1. Daily transaction and fraud summary

CREATE OR REPLACE VIEW DAILY_FRAUD_SUMMARY AS
SELECT
    DATE_TRUNC(
        'DAY',
        TRANSACTION_TIMESTAMP
    ) AS TRANSACTION_DATE,

    COUNT(*) AS TOTAL_TRANSACTIONS,

    SUM(AMOUNT) AS TOTAL_TRANSACTION_AMOUNT,

    COUNT_IF(IS_SUSPICIOUS = TRUE) AS FRAUD_TRANSACTIONS,

    SUM(
        CASE
            WHEN IS_SUSPICIOUS = TRUE
            THEN AMOUNT
            ELSE 0
        END
    ) AS FRAUD_AMOUNT,

    ROUND(
        COUNT_IF(IS_SUSPICIOUS = TRUE)
        * 100.0
        / NULLIF(COUNT(*), 0),
        2
    ) AS FRAUD_RATE_PERCENT

FROM FACT_TRANSACTIONS

GROUP BY
    DATE_TRUNC(
        'DAY',
        TRANSACTION_TIMESTAMP
    );


-- 2. Customer fraud summary

CREATE OR REPLACE VIEW CUSTOMER_FRAUD_SUMMARY AS
SELECT
    CUSTOMER_ID,

    COUNT(*) AS TOTAL_TRANSACTIONS,

    SUM(AMOUNT) AS TOTAL_AMOUNT,

    COUNT_IF(IS_SUSPICIOUS = TRUE) AS SUSPICIOUS_TRANSACTIONS,

    SUM(
        CASE
            WHEN IS_SUSPICIOUS = TRUE
            THEN AMOUNT
            ELSE 0
        END
    ) AS SUSPICIOUS_AMOUNT,

    MAX(RISK_SCORE) AS MAX_RISK_SCORE

FROM FACT_TRANSACTIONS

GROUP BY
    CUSTOMER_ID;


-- 3. Merchant fraud summary

CREATE OR REPLACE VIEW MERCHANT_FRAUD_SUMMARY AS
SELECT
    MERCHANT_ID,

    COUNT(*) AS TOTAL_TRANSACTIONS,

    SUM(AMOUNT) AS TOTAL_AMOUNT,

    COUNT_IF(IS_SUSPICIOUS = TRUE) AS SUSPICIOUS_TRANSACTIONS,

    SUM(
        CASE
            WHEN IS_SUSPICIOUS = TRUE
            THEN AMOUNT
            ELSE 0
        END
    ) AS SUSPICIOUS_AMOUNT,

    ROUND(
        COUNT_IF(IS_SUSPICIOUS = TRUE)
        * 100.0
        / NULLIF(COUNT(*), 0),
        2
    ) AS FRAUD_RATE_PERCENT

FROM FACT_TRANSACTIONS

GROUP BY
    MERCHANT_ID;


-- 4. Regional fraud summary

CREATE OR REPLACE VIEW REGIONAL_FRAUD_SUMMARY AS
SELECT
    CITY,

    COUNT(*) AS TOTAL_TRANSACTIONS,

    SUM(AMOUNT) AS TOTAL_AMOUNT,

    COUNT_IF(IS_SUSPICIOUS = TRUE) AS SUSPICIOUS_TRANSACTIONS,

    SUM(
        CASE
            WHEN IS_SUSPICIOUS = TRUE
            THEN AMOUNT
            ELSE 0
        END
    ) AS SUSPICIOUS_AMOUNT

FROM FACT_TRANSACTIONS

GROUP BY
    CITY;


-- 5. High-risk transactions

CREATE OR REPLACE VIEW HIGH_RISK_TRANSACTIONS AS
SELECT
    TRANSACTION_ID,
    CUSTOMER_ID,
    MERCHANT_ID,
    TRANSACTION_TIMESTAMP,
    AMOUNT,
    CURRENCY,
    CITY,
    RISK_SCORE,
    RISK_LEVEL,
    FRAUD_REASONS,
    IS_SUSPICIOUS

FROM FACT_TRANSACTIONS

WHERE RISK_LEVEL = 'HIGH'

ORDER BY
    RISK_SCORE DESC,
    TRANSACTION_TIMESTAMP DESC;
